language: python

# safelist
branches:
  only:
  - master
  - develop

addons_gcc49: &gcc49
  apt:
    sources: ['ubuntu-toolchain-r-test' ]
    packages: ['g++-4.9', 'gcc-4.9']
addons_gcc5: &gcc5
  apt:
    sources: ['ubuntu-toolchain-r-test' ]
    packages: ['g++-5', 'gcc-5']
addons_gcc6: &gcc6
  apt:
    sources: ['ubuntu-toolchain-r-test' ]
    packages: ['g++-6', 'gcc-6']
addons_clang38: &clang38
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
    packages: ['clang-3.8']

jobs:
  fast_finish: true
  include:
    - python: "2.7"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "2.7"
      env: CXX=g++-5
      addons: *gcc5
    - python: "2.7"
      env: CXX=g++-6
      addons: *gcc6
    - python: "2.7"
      env: CXX=clang++-3.8
      addons: *clang38
    - python: "3.3"
      env: CXX=g++-4.9
      addons: *gcc49
      dist: trusty # no Python 3.3 archive for Xenial (16.04)
    - python: "3.3"
      env: CXX=g++-5
      addons: *gcc5
      dist: trusty
    - python: "3.3"
      env: CXX=g++-6
      addons: *gcc6
      dist: trusty
    - python: "3.3"
      env: CXX=clang++-3.8
      addons: *clang38
      dist: trusty
    - python: "3.4"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.4"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.4"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.4"
      env: CXX=clang++-3.8
      addons: *clang38
    - python: "3.5"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.5"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.5"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.5"
      env: CXX=clang++-3.8
      addons: *clang38
    - python: "3.6"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.6"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.6"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.6"
      env: CXX=clang++-3.8
      addons: *clang38
    - python: "3.7"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.7"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.7"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.7"
      env: CXX=clang++-3.8
      addons: *clang38
    - python: "3.8"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.8"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.8"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.8"
      env: CXX=clang++-3.8
      addons: *clang38
    - python: "3.9"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.9"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.9"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.9"
      env: CXX=clang++-3.8
      addons: *clang38
# https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell

os: linux

dist: xenial

install:
  - pip3 install --upgrade pip
  - pip3 install numpy
  - pip3 install .

# see https://github.com/travis-ci/docs-travis-ci-com/issues/982
script: python3 -m pytest || python -m pytest
