language: python

addons_shortcuts:
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test' ]
      packages: ['g++-4.9', 'gcc-4.9']
  addons_gcc5: &gcc5
    apt:
      sources: ['ubuntu-toolchain-r-test' ]
      packages: ['g++-5', 'gcc-5']
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test' ]
      packages: ['g++-6', 'gcc-6']
  addons_clang4: &clang4
    apt:
      sources: ['ubuntu-toolchain-r-test' ]
      packages: ['clang-4']

matrix:
  include:
    - python: "2.7"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "2.7"
      env: CXX=g++-5
      addons: *gcc5
    - python: "2.7"
      env: CXX=g++-6
      addons: *gcc6
    - python: "2.7"
      env: CXX=clang++-4
      addons: *clang4
    - python: "3.3"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.3"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.3"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.3"
      env: CXX=clang++-4
      addons: *clang4
    - python: "3.4"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.4"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.4"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.4"
      env: CXX=clang++-4
      addons: *clang4
    - python: "3.5"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.5"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.5"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.5"
      env: CXX=clang++-4
      addons: *clang4
    - python: "3.6"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.6"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.6"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.6"
      env: CXX=clang++-4
      addons: *clang4
    - python: "3.7-dev"
      env: CXX=g++-4.9
      addons: *gcc49
    - python: "3.7-dev"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.7-dev"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.7-dev"
      env: CXX=clang++-4
      addons: *clang4
os:
  - linux
#  - osx # See https://github.com/travis-ci/travis-ci/issues/4729

install:
  - pip install .

script: pytest