language: python

addons_shortcuts:
  addons_gcc5: &gcc5
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-5', 'gcc-5']
  addons_gcc6: &gcc6
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-6', 'gcc-6']

matrix:
  include:
    - python: "2.7"
      env: CXX=g++-5
      addons: *gcc5
    - python: "2.7"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.3"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.3"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.4"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.4"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.5"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.5"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.6"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.6"
      env: CXX=g++-6
      addons: *gcc6
    - python: "3.7-dev"
      env: CXX=g++-5
      addons: *gcc5
    - python: "3.7-dev"
      env: CXX=g++-6
      addons: *gcc6

os:
  - linux
#  - osx # See https://github.com/travis-ci/travis-ci/issues/4729

install:
  - pip install .

script: pytest